global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ohpm-services'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/api/metrics'
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
